[[news]]
date = "2025-02"
content = "Participated in the research on 'Self-Supervised Ultrasound Image Denoising Guided by Prior Information' (National Invention Patent applied), serving as a Core Contributor."

[[news]]
date = "2025-11"
content = "Joined the Computational Biology Lab, participating in research on automatic annotation and intelligent diagnosis of echocardiography images."

[[news]]
date = "2026"
content = "Awarded Meritorious Winner in the Mathematical Contest in Modeling (MCM/ICM)."

[[news]]
date = "2026"
content = "Won the National 2nd Prize in the 'Lanqiao Cup' Digital Technology Application Innovation Competition."