type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "Meritorious Winner (M奖)"
subtitle = "美国大学生数学建模竞赛 (MCM/ICM)"
date = "2026"
content = "主要负责代码编写与论文撰写。"

[[items]]
title = "全国二等奖"
subtitle = "“蓝桥杯”数字科技应用创新赛"
date = "2026"
content = "多模态AR人机交互项目"

[[items]]
title = "ACM 集训队成员"
subtitle = "中国海洋大学"
date = "2024"
content = "大二上通过校内竞赛选拔加入校 ACM 集训队。"

[[items]]
title = "蓝桥杯省奖"
subtitle = "算法竞赛"
date = "2024"
content = "蓝桥杯程序设计竞赛省级奖项。"

[[items]]
title = "综合排名 2/21"
subtitle = "中国海洋大学"
date = "2025"
content = "软件工程（五八卓越人才班）综合排名第二。"
