[[news]]
date = "2025-02"
content = "参与 基于先验信息引导的自监督超声图像去噪研究（申请发明专利），担任 Core Contributor。"

[[news]]
date = "2025-11"
content = "加入计算生物学课题组，参与心脏超声影像自动标注与智能诊断研究。"

[[news]]
date = "2026"
content = "获得美国大学生数学建模竞赛 Meritorious Winner (M奖)。"

[[news]]
date = "2026"
content = "获得蓝桥杯数字科技应用创新赛全国二等奖。"
